services:
  - type: web
    name: personal-ai-website
    env: node 18
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production 