services:
  - type: web
    name: personal-ai-website
    env: node 20
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: USE_PROXY
        value: false
      - key: API_TIMEOUT_MS
        value: 60000 